TASK13: Selenium practice
veraaleksandrovna/AQA_Lab-1 pull request #10
Opened 2022-03-30 21:16 UTC by veraaleksandrovna

2022-04-12 16:25 UTC, Maria-Dolia requested changes

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/BaseClasses/BaseTest.cs
> +}
Гит же подсказывает

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/BaseClasses/BaseTest.cs
> +        _driver.Quit();
А если нал драйвер?

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorPage.cs
> +    private const string BorderValueWallDist = "100";
Лучше в какой нибудь объект

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorPage.cs
> +    private IWebElement ActualLTrash => _driver.FindElement(By.XPath("//*[@id=\"l_trash\"]/ b"));
можно сократить дублирование

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorPage.cs
> +    private const string BorderValueWallDist = "100";
Да и вообще эти данные с теста нужно принимать , чтобы иметь гибкое решение

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorTests.cs
> +    public void LaminateCalculatorCheck_Data_Test()
Нейминг .....

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorTests.cs
> +        Thread.Sleep(3000);
испольование   Thread.Sleep крайне нежелательно  
Вдруг понадобится больше времени или меньше

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/LaminateCalculator/LaminateCalculatorTests.cs
> +        Assert.AreEqual(ExpectedLOver, actualLOver);
Обернуть в малтипл

2022-04-12 16:25 UTC, Maria-Dolia commented on SelemiumTask/RehauCalculator/RehauCalculatorTests.cs
> +        var count = _driver.FindElement(By.ClassName("buttHFcalc"));
А пейджа где?

2022-04-12 16:26 UTC, Maria-Dolia commented
Предварительно 6

2022-04-12 19:45 UTC, veraaleksandrovna commented on SelemiumTask/BaseClasses/BaseTest.cs
> +        _driver.Quit();
А как он может быть нал?

2022-04-12 19:46 UTC, veraaleksandrovna commented on SelemiumTask/LaminateCalculator/LaminateCalculatorPage.cs
> +    private const string BorderValueWallDist = "100";
Как их принимать с теста ?

2022-04-18 19:19 UTC, mashadolya approved these changes

2022-04-18 19:19 UTC, mashadolya commented on SelemiumTask/BaseClasses/BaseTest.cs
> +        _driver.Quit();
driver = null;

2022-04-18 21:10 UTC, closed without merging