Les 2/task 2 .net basic operations
veraaleksandrovna/AQA_Lab-1 pull request #3
Opened 2022-02-08 21:34 UTC by veraaleksandrovna

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +class Program
Нужно везде указывать модификаторы доступа(классы, методы)

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +        string FirstName = Console.ReadLine();
Лучше использовать var

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +
Сode conventions, ссылки были указаны в презентации

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +            if (date > DateTime.Now)
Для обработки даты приема лучше будет создать отдельный метод

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +    static string UppercaseFirst(string s)
Используй полное и понятное наименование переменной, пожалуйста

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +throw new ArgumentNullException();
Отсутствует сообщение об ошибке, при неправильно вводе(не ясно какое именно из полей было введено неверно)

2022-02-10 17:34 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +}
Следует добавлять пустую строку в конце каждого файла.
Общее: Отсутствует форматирование кода. Задача решена не до конца. Нужно переделать.

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +    internal class Program
Модификатор доступа - public

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +        private static readonly float USD = 2.5712f;
Лучше использовать и создавать отдельный класс для констант для хранения неизменяемой информации

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +
Между полями не должно быть пустой линии

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +        //private static readonly float BYN = 1f;
Не пушим закоменченный код,а если и есть необходимсоть, то используем специальные комментарии , такие как DEV_NOTE или TO_DO

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +
Code Convention.  Так же есть встроенное форматирование, можно использовать hotkeys, характерные для твоей IDE.
https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +        private static float Convert(string inCurr,string outCurr,float sum)
1. Двойная конвертация, логику лучше доработать.   
2. Создаем отдельный классы для вынесения логики конвертации.

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +            float tempsum = 0f;
Используй var

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                case "usd":
Если текст в коде встречается больше двух раз ('usd' и т.д), то выносится в константы, чтобы избежать дублирования

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +        private static void InputCurrencySumAndConvert()
Разбить метод на вызовы отдельных методов (произвести декомпозицию метода)

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                Console.WriteLine("Введите сумму, которую вы хотите конвертировать:");
Форматирование кода, лишние пробелы

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                return;
Здесь нет необходимости в  return

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                Console.WriteLine("{0} {1}", Math.Round(Convert(inCurrency, outCurrency, sum), 2), outCurrency);
"Math.Round(Convert(inCurrency, outCurrency, sum), 2)" - можно вынести в отдельную конструкцию

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                //Console.WriteLine(answer);
Если пользователь введет только число, без указания валюты - не обработано

2022-02-10 17:34 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                    Console.WriteLine("Неправильный ввод суммы!");
Этот блок не будет отображен, так как в начале метода ты ощищаешь.

2022-02-11 19:10 UTC, mashadolya requested changes

2022-02-11 19:10 UTC, mashadolya commented on Task/Bot_Task1/Program.cs
> +        DateTime date = Convert.ToDateTime(Console.ReadLine());
var

2022-02-11 19:10 UTC, mashadolya commented on Task/Bot_Task1/Program.cs
> +    }
скобки
писала всем в чат

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +        public static readonly string rub = "rub";
в отдельный класс 
Currencу например

```
var eur = new Currency {
Type= Eur,
Value = 2.9314f
}
```

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +                case "rub":
и зачем мы выше объявляли такие же строки

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +            return null;
Зачем ретурн нал?)
Почему нал?

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +        private static float Convert(string inCurr, string outCurr, float sum)
никаких сокращений в нейминге переменных, методов и тд

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +                if (answparse.Length > 2)
что за 2? почему два? 
Никаких магический цифр в коде быть не должно

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +                float sum = 0f;
вар

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +                }
Мы должны писать код таким образом, чтобы любой другой человек мог его спокойно понять просто читая название переменных, методов 
Я не понимаю для чего это нужно

2022-02-11 19:10 UTC, mashadolya commented on Task/Bot_Task1/Program.cs
> +            throw new ArgumentNullException();
так а как попробовать еще раз, если тут исключение бросается и не обрабатывается в дальнейшем

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +                var inCurrency = answparse[1].ToLower();
answparse[1].ToLower(); выше уже есть
 дублиирование

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +            for (int i = 0; i < Array.MaxLength; i++)
а почему до Array.MaxLength? 🧐

2022-02-11 19:10 UTC, mashadolya commented on Task/Currency_convert/Program.cs
> +            return tempsum;
нейминг

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +namespace Bot
Читай примечания IDE, она явно тебе советует переименовать на Bot_Task1 (или переименуй сам проект на Bot)

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +public class Program
static

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +        var firstName = Console.ReadLine();
А что если пользователь введет только цифры или иной ошибочный ввод, например пробел?

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +        DateTime date = Convert.ToDateTime(Console.ReadLine());
По умолчанию DateTime принимает значения в формате month/day/year, то есть в текущей реализации при вводе 13/07/2022 -> ошибка

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +        DateHandler(date);
При корректном вводе даты в результате успешной записи время приема 00.00.00 логичнее было
бы через ранодом задать более правдоподобное время или отформатировать вывод даты (отбросить время)

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +    }
Должна быть реализована возможность ввести дату повторно.
В текущей реализации при неверном введении даты ты все равно будешь записан на прием

2022-02-11 20:28 UTC, julsinkevich commented on Task/Bot_Task1/Program.cs
> +}
форматирование кода

2022-02-11 20:28 UTC, julsinkevich commented on Task/Currency_convert/Constants.cs
> +    public static readonly float RUB = 0.034155
Отсутствие "f;"-> код не скомпилируется

2022-02-11 20:28 UTC, julsinkevich commented on Task/Currency_convert/Constants.cs
> +    public static readonly float RUB = 0.034155
static Если статичные члены класса, это статичный и метод

2022-02-11 20:28 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +using static Task1.Constants;
Из-за не соответствующего наименования файлов - проблемы с using. Читай подсказки IDE

2022-02-11 20:28 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +    public class Program
static

2022-02-11 20:28 UTC, julsinkevich commented on Task/Currency_convert/Program.cs
> +                case "rub":
нерабочая конвертация

2022-02-14 21:48 UTC, veraaleksandrovna commented on Task/Bot_Task1/Program.cs
> +        DateTime date = Convert.ToDateTime(Console.ReadLine());
но по умолчанию наоборот day/maonth/year, как в коде и когда программа запускается там нельзя ввести второе значение больше 12, а не 1

2022-04-18 21:11 UTC, closed without merging