Les 4/task 4 classes objects and methods
veraaleksandrovna/AQA_Lab-1 pull request #5
Opened 2022-02-11 20:26 UTC by veraaleksandrovna

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Candidate.cs
> +    public class Candidate
Создайте папку «Models», в которой будут «Employee» и «Candidate».

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Candidate.cs
> +        public int Id { get; set; }
Пустая строка между свойствами.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Candidate.cs
> +        public string Name { get; set; }
Создайте отдельный класс Human с общими свойствами для Candidate и Employee.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Candidate.cs
> +using System.Threading.Tasks;
Удаляй, то что не используется в данном классе.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Employee.cs
> +        public string LastName { get; set; }
Пустая строка между свойствами.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Employee.cs
> +using System.Text;
Удаляй, то что не используется в данном классе.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/IPrintable.cs
> +using System.Text;
Удаляй, то что не используется в данном классе.

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/IPrintable.cs
> +    public interface IPrintable
Создайте папку «Interface», в которой будет «IPrintabl» .

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/IPrintable.cs
> +        public void Print(Candidate person);
public void Print();
Реализуй в классаx Employee и Candidate текущий интерфейс.
Пропадет класс Printer

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Program.cs
> +                printer.Print(item);
нет сортировки

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Program.cs
> +                printer.Print(item);
нет сортировки

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Program.cs
> +            var rand = new Random();
Создай отдельный метод, чтобы избежать дублирования в GetCandidates() и GetEmployees()

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Program.cs
> +                var name = Console.ReadLine();
Заполнение информаии через Bogus

2022-02-13 13:21 UTC, julsinkevich commented on Task/Task/Program.cs
> +                    Id = id++,
Для ID лучше использовать Guid.

И выполни данное задание с помощью Bogus https://github.com/bchavez/Bogus

2022-02-14 17:29 UTC, mashadolya requested changes
1. Слишком много дублирования кода
2. Код конвеншены не соблюдаются 
3. В задании не было указано вводить какие либо данные с консоли

2022-04-18 21:11 UTC, closed without merging